export const countriesISO = [
  { alpha2: "AF", name: "Afghanistan", phonePrefix: "+93" },
  { alpha2: "AX", name: "Åland Islands", phonePrefix: "+358" },
  { alpha2: "AL", name: "Albania", phonePrefix: "+355" },
  { alpha2: "DE", name: "Germany", phonePrefix: "+49" },
  { alpha2: "AD", name: "Andorra", phonePrefix: "+376" },
  { alpha2: "AO", name: "Angola", phonePrefix: "+244" },
  { alpha2: "AI", name: "Anguilla", phonePrefix: "+1264" },
  { alpha2: "AQ", name: "Antarctica", phonePrefix: "+672" },
  { alpha2: "AG", name: "Antigua and Barbuda", phonePrefix: "+1268" },
  { alpha2: "SA", name: "Saudi Arabia", phonePrefix: "+966" },
  { alpha2: "DZ", name: "Algeria", phonePrefix: "+213" },
  { alpha2: "AR", name: "Argentina", phonePrefix: "+54" },
  { alpha2: "AM", name: "Armenia", phonePrefix: "+374" },
  { alpha2: "AW", name: "Aruba", phonePrefix: "+297" },
  { alpha2: "AU", name: "Australia", phonePrefix: "+61" },
  { alpha2: "AT", name: "Austria", phonePrefix: "+43" },
  { alpha2: "AZ", name: "Azerbaijan", phonePrefix: "+994" },
  { alpha2: "BS", name: "Bahamas", phonePrefix: "+1242" },
  { alpha2: "BD", name: "Bangladesh", phonePrefix: "+880" },
  { alpha2: "BB", name: "Barbados", phonePrefix: "+1246" },
  { alpha2: "BH", name: "Bahrain", phonePrefix: "+973" },
  { alpha2: "BE", name: "Belgium", phonePrefix: "+32" },
  { alpha2: "BZ", name: "Belize", phonePrefix: "+501" },
  { alpha2: "BJ", name: "Benin", phonePrefix: "+229" },
  { alpha2: "BM", name: "Bermuda", phonePrefix: "+1441" },
  { alpha2: "BY", name: "Belarus", phonePrefix: "+375" },
  { alpha2: "BO", name: "Bolivia", phonePrefix: "+591" },
  {
    alpha2: "BQ",
    name: "Bonaire, Sint Eustatius and Saba",
    phonePrefix: "+5997",
  },
  { alpha2: "BA", name: "Bosnia and Herzegovina", phonePrefix: "+387" },
  { alpha2: "BW", name: "Botswana", phonePrefix: "+267" },
  { alpha2: "BR", name: "Brazil", phonePrefix: "+55" },
  { alpha2: "BN", name: "Brunei Darussalam", phonePrefix: "+673" },
  { alpha2: "BG", name: "Bulgaria", phonePrefix: "+359" },
  { alpha2: "BF", name: "Burkina Faso", phonePrefix: "+226" },
  { alpha2: "BI", name: "Burundi", phonePrefix: "+257" },
  { alpha2: "BT", name: "Bhutan", phonePrefix: "+975" },
  { alpha2: "CV", name: "Cabo Verde", phonePrefix: "+238" },
  { alpha2: "KH", name: "Cambodia", phonePrefix: "+855" },
  { alpha2: "CM", name: "Cameroon", phonePrefix: "+237" },
  { alpha2: "CA", name: "Canada", phonePrefix: "+1" },
  { alpha2: "QA", name: "Qatar", phonePrefix: "+974" },
  { alpha2: "TD", name: "Chad", phonePrefix: "+235" },
  { alpha2: "CL", name: "Chile", phonePrefix: "+56" },
  { alpha2: "CN", name: "China", phonePrefix: "+86" },
  { alpha2: "CY", name: "Cyprus", phonePrefix: "+357" },
  { alpha2: "CO", name: "Colombia", phonePrefix: "+57" },
  { alpha2: "KM", name: "Comoros", phonePrefix: "+269" },
  {
    alpha2: "KP",
    name: "Korea (Democratic People's Republic of)",
    phonePrefix: "+850",
  },
  { alpha2: "KR", name: "Korea, Republic of", phonePrefix: "+82" },
  { alpha2: "CI", name: "Côte d'Ivoire", phonePrefix: "+225" },
  { alpha2: "CR", name: "Costa Rica", phonePrefix: "+506" },
  { alpha2: "HR", name: "Croatia", phonePrefix: "+385" },
  { alpha2: "CU", name: "Cuba", phonePrefix: "+53" },
  { alpha2: "CW", name: "Curaçao", phonePrefix: "+599" },
  { alpha2: "DK", name: "Denmark", phonePrefix: "+45" },
  { alpha2: "DM", name: "Dominica", phonePrefix: "+1" },
  { alpha2: "EC", name: "Ecuador", phonePrefix: "+593" },
  { alpha2: "EG", name: "Egypt", phonePrefix: "+20" },
  { alpha2: "SV", name: "El Salvador", phonePrefix: "+503" },
  { alpha2: "AE", name: "United Arab Emirates", phonePrefix: "+971" },
  { alpha2: "ER", name: "Eritrea", phonePrefix: "+291" },
  { alpha2: "SK", name: "Slovakia", phonePrefix: "+421" },
  { alpha2: "SI", name: "Slovenia", phonePrefix: "+386" },
  { alpha2: "ES", name: "Spain", phonePrefix: "+34" },
  { alpha2: "US", name: "United States of America", phonePrefix: "+1" },
  { alpha2: "EE", name: "Estonia", phonePrefix: "+372" },
  { alpha2: "ET", name: "Ethiopia", phonePrefix: "+251" },
  { alpha2: "PH", name: "Philippines", phonePrefix: "+63" },
  { alpha2: "FI", name: "Finland", phonePrefix: "+358" },
  { alpha2: "FJ", name: "Fiji", phonePrefix: "+679" },
  { alpha2: "FR", name: "France", phonePrefix: "+33" },
  { alpha2: "GA", name: "Gabon", phonePrefix: "+241" },
  { alpha2: "GM", name: "Gambia", phonePrefix: "+220" },
  { alpha2: "GE", name: "Georgia", phonePrefix: "+995" },
  { alpha2: "GH", name: "Ghana", phonePrefix: "+233" },
  { alpha2: "GI", name: "Gibraltar", phonePrefix: "+350" },
  { alpha2: "GD", name: "Grenada", phonePrefix: "+1" },
  { alpha2: "GR", name: "Greece", phonePrefix: "+30" },
  { alpha2: "GL", name: "Greenland", phonePrefix: "+299" },
  { alpha2: "GP", name: "Guadeloupe", phonePrefix: "+590" },
  { alpha2: "GU", name: "Guam", phonePrefix: "+1" },
  { alpha2: "GT", name: "Guatemala", phonePrefix: "+502" },
  { alpha2: "GF", name: "French Guiana", phonePrefix: "+594" },
  { alpha2: "GG", name: "Guernsey", phonePrefix: "+44 1481" },
  { alpha2: "GN", name: "Guinea", phonePrefix: "+224" },
  { alpha2: "GW", name: "Guinea-Bissau", phonePrefix: "+245" },
  { alpha2: "GQ", name: "Equatorial Guinea", phonePrefix: "+240" },
  { alpha2: "GY", name: "Guyana", phonePrefix: "+592" },
  { alpha2: "HT", name: "Haiti", phonePrefix: "+509" },
  { alpha2: "HN", name: "Honduras", phonePrefix: "+504" },
  { alpha2: "HK", name: "Hong Kong", phonePrefix: "+852" },
  { alpha2: "HU", name: "Hungary", phonePrefix: "+36" },
  { alpha2: "IN", name: "India", phonePrefix: "+91" },
  { alpha2: "ID", name: "Indonesia", phonePrefix: "+62" },
  { alpha2: "IQ", name: "Iraq", phonePrefix: "+964" },
  { alpha2: "IR", name: "Iran", phonePrefix: "+98" },
  { alpha2: "IE", name: "Ireland", phonePrefix: "+353" },
  { alpha2: "BV", name: "Bouvet Island", phonePrefix: "+47" },
  { alpha2: "IM", name: "Isle of Man", phonePrefix: "+44 1624" },
  { alpha2: "CX", name: "Christmas Island", phonePrefix: "+61" },
  { alpha2: "IS", name: "Iceland", phonePrefix: "+354" },
  { alpha2: "KY", name: "Cayman Islands", phonePrefix: "+1" },
  { alpha2: "CC", name: "Cocos (Keeling) Islands", phonePrefix: "+61" },
  { alpha2: "CK", name: "Cook Islands", phonePrefix: "+682" },
  { alpha2: "FO", name: "Faroe Islands", phonePrefix: "+298" },

  {
    alpha2: "GS",
    name: "South Georgia and the South Sandwich Islands",
    phonePrefix: "+500",
  },
  {
    alpha2: "HM",
    name: "Heard Island and McDonald Islands",
    phonePrefix: "+61",
  },
  { alpha2: "FK", name: "Falkland Islands (Malvinas)", phonePrefix: "+500" },
  { alpha2: "MP", name: "Northern Mariana Islands", phonePrefix: "+1" },
  { alpha2: "MH", name: "Marshall Islands", phonePrefix: "+692" },
  { alpha2: "PN", name: "Pitcairn", phonePrefix: "+64" },
  { alpha2: "SB", name: "Solomon Islands", phonePrefix: "+677" },
  { alpha2: "TC", name: "Turks and Caicos Islands", phonePrefix: "+1" },
  {
    alpha2: "UM",
    name: "United States Minor Outlying Islands",
    phonePrefix: "+1",
  },
  { alpha2: "VG", name: "Virgin Islands (British)", phonePrefix: "+1" },
  { alpha2: "VI", name: "Virgin Islands (U.S.)", phonePrefix: "+1" },
  { alpha2: "IL", name: "Israel", phonePrefix: "+972" },
  { alpha2: "IT", name: "Italy", phonePrefix: "+39" },
  { alpha2: "JM", name: "Jamaica", phonePrefix: "+1" },
  { alpha2: "JP", name: "Japan", phonePrefix: "+81" },
  { alpha2: "JE", name: "Jersey", phonePrefix: "+44-1534" },
  { alpha2: "JO", name: "Jordan", phonePrefix: "+962" },
  { alpha2: "KZ", name: "Kazakhstan", phonePrefix: "+7" },
  { alpha2: "KE", name: "Kenya", phonePrefix: "+254" },
  { alpha2: "KG", name: "Kyrgyzstan", phonePrefix: "+996" },
  { alpha2: "KI", name: "Kiribati", phonePrefix: "+686" },
  { alpha2: "KW", name: "Kuwait", phonePrefix: "+965" },
  {
    alpha2: "LA",
    name: "Lao People's Democratic Republic",
    phonePrefix: "+856",
  },
  { alpha2: "LS", name: "Lesotho", phonePrefix: "+266" },
  { alpha2: "LV", name: "Latvia", phonePrefix: "+371" },
  { alpha2: "LB", name: "Lebanon", phonePrefix: "+961" },
  { alpha2: "LR", name: "Liberia", phonePrefix: "+231" },
  { alpha2: "LY", name: "Libya", phonePrefix: "+218" },
  { alpha2: "LI", name: "Liechtenstein", phonePrefix: "+423" },
  { alpha2: "LT", name: "Lithuania", phonePrefix: "+370" },
  { alpha2: "LU", name: "Luxembourg", phonePrefix: "+352" },
  { alpha2: "MO", name: "Macao", phonePrefix: "+853" },
  { alpha2: "MK", name: "North Macedonia", phonePrefix: "+389" },
  { alpha2: "MG", name: "Madagascar", phonePrefix: "+261" },
  { alpha2: "MY", name: "Malaysia", phonePrefix: "+60" },
  { alpha2: "MW", name: "Malawi", phonePrefix: "+265" },
  { alpha2: "MV", name: "Maldives", phonePrefix: "+960" },
  { alpha2: "ML", name: "Mali", phonePrefix: "+223" },
  { alpha2: "MT", name: "Malta", phonePrefix: "+356" },
  { alpha2: "MA", name: "Morocco", phonePrefix: "+212" },
  { alpha2: "MQ", name: "Martinique", phonePrefix: "+596" },
  { alpha2: "MU", name: "Mauritius", phonePrefix: "+230" },
  { alpha2: "MR", name: "Mauritania", phonePrefix: "+222" },
  { alpha2: "YT", name: "Mayotte", phonePrefix: "+262" },
  { alpha2: "MX", name: "Mexico", phonePrefix: "+52" },
  { alpha2: "FM", name: "Micronesia", phonePrefix: "+691" },
  { alpha2: "MD", name: "Moldova, Republic of", phonePrefix: "+373" },
  { alpha2: "MC", name: "Monaco", phonePrefix: "+377" },
  { alpha2: "MN", name: "Mongolia", phonePrefix: "+976" },
  { alpha2: "ME", name: "Montenegro", phonePrefix: "+382" },
  { alpha2: "MS", name: "Montserrat", phonePrefix: "+1" },
  { alpha2: "MZ", name: "Mozambique", phonePrefix: "+258" },
  { alpha2: "MM", name: "Myanmar", phonePrefix: "+95" },
  { alpha2: "NA", name: "Namibia", phonePrefix: "+264" },
  { alpha2: "NR", name: "Nauru", phonePrefix: "+674" },
  { alpha2: "NP", name: "Nepal", phonePrefix: "+977" },
  { alpha2: "NI", name: "Nicaragua", phonePrefix: "+505" },
  { alpha2: "NE", name: "Niger", phonePrefix: "+227" },
  { alpha2: "NG", name: "Nigeria", phonePrefix: "+234" },
  { alpha2: "NU", name: "Niue", phonePrefix: "+683" },
  { alpha2: "NF", name: "Norfolk Island", phonePrefix: "+672" },
  { alpha2: "NO", name: "Norway", phonePrefix: "+47" },
  { alpha2: "NC", name: "New Caledonia", phonePrefix: "+687" },
  { alpha2: "NZ", name: "New Zealand", phonePrefix: "+64" },
  { alpha2: "OM", name: "Oman", phonePrefix: "+968" },
  { alpha2: "NL", name: "Netherlands", phonePrefix: "+31" },
  { alpha2: "PK", name: "Pakistan", phonePrefix: "+92" },
  { alpha2: "PW", name: "Palau", phonePrefix: "+680" },
  { alpha2: "PS", name: "Palestine, State of", phonePrefix: "+970" },
  { alpha2: "PA", name: "Panama", phonePrefix: "+507" },
  { alpha2: "PG", name: "Papua New Guinea", phonePrefix: "+675" },
  { alpha2: "PY", name: "Paraguay", phonePrefix: "+595" },
  { alpha2: "PE", name: "Perú", phonePrefix: "+51" },
  { alpha2: "PF", name: "French Polynesia", phonePrefix: "+689" },
  { alpha2: "PL", name: "Poland", phonePrefix: "+48" },
  { alpha2: "PT", name: "Portugal", phonePrefix: "+351" },
  { alpha2: "PR", name: "Puerto Rico", phonePrefix: "+1" },
  {
    alpha2: "GB",
    name: "United Kingdom of Great Britain and Northern Ireland",
    phonePrefix: "+44",
  },
  { alpha2: "EH", name: "Western Sahara", phonePrefix: "+212" },
  { alpha2: "CF", name: "Central African Republic", phonePrefix: "+236" },
  { alpha2: "CZ", name: "Czechia", phonePrefix: "+420" },
  { alpha2: "CG", name: "Congo", phonePrefix: "+242" },
  {
    alpha2: "CD",
    name: "Congo, Democratic Republic of the",
    phonePrefix: "+243",
  },
  { alpha2: "DO", name: "Dominican Republic", phonePrefix: "+1" },
  { alpha2: "RE", name: "Réunion", phonePrefix: "+262" },
  { alpha2: "RW", name: "Rwanda", phonePrefix: "+250" },
  { alpha2: "RO", name: "Romania", phonePrefix: "+40" },
  { alpha2: "RU", name: "Russian Federation", phonePrefix: "+7" },
  { alpha2: "WS", name: "Samoa", phonePrefix: "+685" },
  { alpha2: "AS", name: "American Samoa", phonePrefix: "+1" },
  { alpha2: "BL", name: "Saint Barthélemy", phonePrefix: "+590" },
  { alpha2: "KN", name: "Saint Kitts and Nevis", phonePrefix: "+1" },
  { alpha2: "SM", name: "San Marino", phonePrefix: "+378" },
  { alpha2: "MF", name: "Saint Martin (French part)", phonePrefix: "+590" },
  { alpha2: "PM", name: "Saint Pierre and Miquelon", phonePrefix: "+508" },
  {
    alpha2: "VC",
    name: "Saint Vincent and the Grenadines",
    phonePrefix: "+1",
  },
  {
    alpha2: "SH",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    phonePrefix: "+290",
  },
  { alpha2: "LC", name: "Saint Lucia", phonePrefix: "+1" },
  { alpha2: "ST", name: "Sao Tome and Principe", phonePrefix: "+239" },
  { alpha2: "SN", name: "Senegal", phonePrefix: "+221" },
  { alpha2: "RS", name: "Serbia", phonePrefix: "+381" },
  { alpha2: "SC", name: "Seychelles", phonePrefix: "+248" },
  { alpha2: "SL", name: "Sierra Leone", phonePrefix: "+232" },
  { alpha2: "SG", name: "Singapore", phonePrefix: "+65" },
  { alpha2: "SX", name: "Sint Maarten (Dutch part)", phonePrefix: "+1" },
  { alpha2: "SY", name: "Syrian Arab Republic", phonePrefix: "+963" },
  { alpha2: "SO", name: "Somalia", phonePrefix: "+252" },
  { alpha2: "LK", name: "Sri Lanka", phonePrefix: "+94" },
  { alpha2: "SZ", name: "Eswatini", phonePrefix: "+268" },
  { alpha2: "ZA", name: "South Africa", phonePrefix: "+27" },
  { alpha2: "SD", name: "Sudan", phonePrefix: "+249" },
  { alpha2: "SS", name: "South Sudan", phonePrefix: "+211" },
  { alpha2: "SE", name: "Sweden", phonePrefix: "+46" },
  { alpha2: "CH", name: "Switzerland", phonePrefix: "+41" },
  { alpha2: "SR", name: "Suriname", phonePrefix: "+597" },
  { alpha2: "SJ", name: "Svalbard and Jan Mayen", phonePrefix: "+47" },
  { alpha2: "TH", name: "Thailand", phonePrefix: "+66" },
  { alpha2: "TW", name: "Taiwan", phonePrefix: "+886" },
  { alpha2: "TZ", name: "Tanzania", phonePrefix: "+255" },
  { alpha2: "TJ", name: "Tajikistan", phonePrefix: "+992" },
  { alpha2: "IO", name: "British Indian Ocean Territory", phonePrefix: "+246" },
  { alpha2: "TF", name: "French Southern Territories", phonePrefix: "+262" },
  { alpha2: "TL", name: "Timor-Leste", phonePrefix: "+670" },
  { alpha2: "TG", name: "Togo", phonePrefix: "+228" },
  { alpha2: "TK", name: "Tokelau", phonePrefix: "+690" },
  { alpha2: "TO", name: "Tonga", phonePrefix: "+676" },
  { alpha2: "TT", name: "Trinidad and Tobago", phonePrefix: "+1" },
  { alpha2: "TN", name: "Tunisia", phonePrefix: "+216" },
  { alpha2: "TM", name: "Turkmenistan", phonePrefix: "+993" },
  { alpha2: "TR", name: "Turkey", phonePrefix: "+90" },
  { alpha2: "TV", name: "Tuvalu", phonePrefix: "+688" },
  { alpha2: "UA", name: "Ukraine", phonePrefix: "+380" },
  { alpha2: "UG", name: "Uganda", phonePrefix: "+256" },
  { alpha2: "UY", name: "Uruguay", phonePrefix: "+598" },
  { alpha2: "UZ", name: "Uzbekistan", phonePrefix: "+998" },
  { alpha2: "VU", name: "Vanuatu", phonePrefix: "+678" },
  { alpha2: "VA", name: "Holy See", phonePrefix: "+379" },
  { alpha2: "VE", name: "Venezuela", phonePrefix: "+58" },
  { alpha2: "VN", name: "Viet Nam", phonePrefix: "+84" },
  { alpha2: "WF", name: "Wallis and Futuna", phonePrefix: "+681" },
  { alpha2: "YE", name: "Yemen", phonePrefix: "+967" },
  { alpha2: "DJ", name: "Djibouti", phonePrefix: "+253" },
  { alpha2: "ZM", name: "Zambia", phonePrefix: "+260" },
  { alpha2: "ZW", name: "Zimbabwe", phonePrefix: "+263" },
];
