export const theme = {
  font_weight: {
    small: "400",
    medium: "500",
    large: "700",
  },
  border_radius: {
    xx_small: ".4em",
    x_small: ".5em",
    small: ".6em",
    medium: ".9em",
    large: "1em",
    x_large: "1.2em",
    xx_large: "1.4em",
    xxx_large: "1.7em",
    percentage_medium: "50%",
    percentage_full: "100%",
  },
  paddings: {
    xx_small: ".3em",
    x_small: ".5em",
    small: ".7em",
    medium: ".9em",
    large: "1em",
    x_large: "1.2em",
    xx_large: "1.4em",
    xxx_large: "1.7em",
  },
  font_sizes: {
    xxx_small: ".6em",
    xx_small: ".7em",
    x_small: ".9em",
    small: "1em",
    medium: "1.1em",
    large: "1.3em",
    x_large: "1.4em",
    xx_large: "1.6em",
    xxx_large: "1.8em",
  },
  colors: {
    primary: "#231473",
    secondary: "#6E3FCB",
    tertiary: "#D7D8FD",
    quaternary: "#F3F3FF",

    success: "#56d66b",
    info: "#0795FF",
    warning: "#F5C203",
    error: "#FC2626",

    heading: "#040c10",
    body: "#171d1f",

    gray: "#959ba1",
    gray2: "#F2F6F8",

    black: "#000000",
    white: "#FFFFFF",
  },
};
